<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>
	  <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
	  <TargetFramework>net8.0-windows10.0.18362</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.2" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ffmpeg.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="readme.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
